config/routes.rb
Rails.application.routes.draw do



  resources :comments
  resources :users


  #get 'about', to: 'pages#about'

resources :articles
resources :accounts
resources :categories, except: [:destory]


get 'signup', to: 'users#new'
post 'users', to: 'users#create'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
#resources :users, except: [:new]
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: {minimum:3,maximum:50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :article_categories
  has_many :article,through: :article_categories
  validates :name, presence: true, length: {minimum: 3,maximum:25 }
  validates_uniqueness_of :name
end

app/models/check.rb
class Check < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :articles
  has_one :accounts
  before_save{ self.email = email.downcase }
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {mininum: 3, maximum:25}

   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

   validates :email,presence: true, length:{maximum:105}, uniqueness: {case_sensitive: false}, format:{with: VALID_EMAIL_REGEX}

   has_secure_password

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
  @articles = Article.paginate(page: params[:page],per_page: 3)
end
def new
  @article = Article.new
  @user = User.new
end
def edit
  @article = Article.find(params[:id])
end

def create
  #render plain: params[:article].inspect
  debugger
  @article = Article.new(article_params)
  @article.user = User.first
#  @article.save
#  redirect_to article_path(@article)
if @article.save
  flash[:success] = "Article was successfully created"
  redirect_to article_path(@article)
else
  render 'new'
end
end


def update
  @article = Article.find(params[:id])
  if @article.update(article_params)
    flash[:success] = "Article was successfully updated"
    redirect_to article_path(@article)

  else
    render 'edit'
  end

end

def show
  @article = Article.find(params[:id])
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
  flash[:danger] ="Article was successfully deleted "
  redirect_to articles_path

end


private
  def article_params
    params.require(:article).permit(:title, :description)

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

  end
  def new

  end
  def show

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
  #render 'new'
  #debugger

  user = User.find_by(email: params[:session][:email].downcase)

  if user && user.authenticate(params[:session][:password])

    session[:user_id] = user.id

    flash[:success] = "You have successfully logged in"

    redirect_to user_path(user)

  else

    flash.now[:danger] = "There was something wrong with your login information"

    render 'new'

  end
end

def destroy
  session[:user_id] = nil
  flash[:success] = "You have logged out"
  redirect_to login_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
      @users = User.paginate(page: params[:page], per_page: 3)
  end
  def new
    @user =User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save

    flash[:success] = "Welcome to the alpha blog #{@user.username}"

    redirect_to articles_path

    else

    render 'new'

  end

end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end

  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page],per_page: 3)
  end

private

def user_params

params.require(:user).permit(:username, :email, :password)

end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})

    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)

    size = options[:size]

    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "img-circle")

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<!-- # <%= link_to "Create new Article", new_article_path, class: "btn btn-xs btn-primary" %> -->

<% obj.each do |article| %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="article-title">

<%= link_to article.title, article_path(article) %>

</div>

<div class="article-body">

<%= truncate(article.description, length: 100) %>

<div class="article-meta-details">

<small>Created by: <%= article.user.username if article.user%>,

<%= time_ago_in_words(article.created_at) %> ago,

last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

</div>



</div>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>


</div>

</div>

</div>

</div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<!--<% if @article.errors.any? %>
<h2>Errors that prvented the article from getting created</h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %><li>
    <% end %>
  </ul>
  <% end %>
-->
<div class='row'>
  <div class='col-md-12'>

      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <div class="control-label col-sm-2">

          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>

</div>
</div>
<div class="form-group">
  <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
          <div class="col-sm-8">
          <%= f.text_area :description,class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit  class: 'btn btn-primary btn-lg'%>
        </div>
      </div>


      <% end %>
      <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>

</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existion article</h1>

<%= render 'form' %>

<!--
<% if @article.errors.any? %>
<h2>Errors that prvented the article from getting created</h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %><li>
    <% end %>
  </ul>
  <% end %>


<%= form_for @article do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>


<% end %>
<%= link_to "Back to articles listing", articles_path %>
-->

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

<!--
<%= link_to "Create new Article", new_article_path, class: "btn btn-xs btn-primary" %>

<% @articles.each do |article| %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="article-title">

<%= link_to article.title, article_path(article) %>

</div>

<div class="article-body">

<%= truncate(article.description, length: 100) %>

<div class="article-meta-details">

<small>Created by: <%= article.user.username if article.user%>,

<%= time_ago_in_words(article.created_at) %> ago,

last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

</div>



</div>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

</div>

</div>

</div>

</div>

<% end %> -->

<!--<h1>List of Articles</h1>
<p>

<%= link_to "Create new article", new_article_path %>

</p>

<table>

<tr>

<th>Title</th>

<th>Description</th>

</tr>

<% @articles.each do |article| %>

<tr>

<td><%= article.title %></td>

<td><%= article.description %></td>

<td><%= link_to 'Edit', edit_article_path(article) %></td>

<td><%= link_to 'Show', article_path(article) %></td>

<td><%= link_to 'Delete',article_path(article),method: :delete, date: {confirm: "Are you sure ?"}%></td>

</tr>

<% end %>

</table>
-->

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>


<%= render 'form' %>
<!--
<% if @article.errors.any? %>
<h2>Errors that prvented the article from getting created</h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %><li>
    <% end %>
  </ul>
  <% end %>




<%= form_for @article do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>


<% end %>
<%= link_to "Back to articles listing", articles_path %>
-->

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<% if @article.user %>
<div class="well col-xs-8 col-xs-offset-2">

  <ul class="listing">

    <div class="row center">

      <div class=" col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

        <li class="article-title">

        <%= link_to @article.user.username, user_path(@article.user) %>

      </li>

      <li><small>
        <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
      </small></li>

    </div>

    </div>

  </ul>
<% end %>

  <h4 class="center description"><strong>Description:</strong></h4>

  <hr>

  <%= simple_format(@article.description) %>

  <div class="article-actions">

    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

    <%= link_to "Delete this article", article_path(@article), method: :delete,

                    data: { confirm: "Are you sure you want to delete the article?"},

                    class: "btn btn-xs btn-danger" %>

    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

  </div>

</div>


<!--<h2 align="center">Title : <%= @article.title %>
  Title: <%= @article.title %>
</p>

<p>
  Description: <%= @article.description %>
</p>
<%= link_to "Edit this article", edit_article_path(@article) %> |
<%= link_to "Back to articles listing", articles_path %>
-->

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>


<%= render 'shared/errors', obj: @user %>


<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit(@user.new_record? ? "Sign up" :"Update account", class: 'btn btn-primary btn-lg') %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

Copyright © <a href="enter in a link here">The Complete Ruby on Rails Developer</a>

by <a href="enter in a link here">Mashrur Hossain</a>

</small>

<nav>

<ul>


</ul>

</nav>

</footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>



<!--<% flash.each do |name,msg| %>
<ul>
  <li><%= msg %></li>
</ul>
<% end %>
-->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="new_article_path">Articles</a> -->
      <%= link_to "New Article", new_article_path, class: " navbar-brand" %>


    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log out',logout_path,method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

  <body>
      <!--
      <% flash.each do |name,msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
      <% end %>
      -->
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navigation' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="panel panel-danger">

<div class="panel-heading">

<h2 class="panel-title">

<%= pluralize(obj.errors.count, "error") %>

prohibited this article from being saved:

</h2>

<div class="panel-body">

<ul>

<% obj.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

</div>

</div>

</div>

</div>

<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>

<div class='col-xs-12'>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit(@user.new_record? ? "Sign up" :"Update account", class: 'btn btn-primary btn-lg') %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

</div>

</div>

</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your Account</h1>

<%= render 'form'%>
<!--
<%= render 'shared/errors', obj: @user %>

<div class='row'>

<div class='col-xs-12'>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit "Update your account", class: 'btn btn-primary btn-lg' %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

</div>

</div>

</div>
-->

app/views/users/index.html.erb
<h1 align="center">All users</h1>
<div align="center">

  <%= will_paginate %>

<% @users.each do |user| %>

  <ul class="listing">

    <div class="row">

      <div class="well col-md-4 col-md-offset-4">

        <li><%= link_to gravatar_for(user), user_path(user) %></li>

        <li class="article-title">

        <%= link_to user.username, user_path(user) %>

      </li>

      <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>

    </div>

    </div>

  </ul>

<% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Users</h1>

<%= render 'form'%>
<!--
<%= render 'shared/errors', obj: @user %>

<div class='row'>

<div class='col-xs-12'>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :username %>

</div>

<div class="col-sm-8">

<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :email %>

</div>

<div class="col-sm-8">

<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>

</div>

</div>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :password %>

</div>

<div class="col-sm-8">

<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit "Sign up", class: 'btn btn-primary btn-lg' %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

</div>

</div>

</div>

-->

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s Page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user,size:150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
    <div class= "center">
      <%= will_paginate @user_articles %>
    </div>
<%= render 'articles/article', obj: @user_articles %>
    <div class= "center">
      <%= will_paginate @user_articles %>
    </div>